### ISSUE TITLE
Face is not selecting 

### ISSUE THREAD

**Issue by davidsa** [mapeveri/Angular-rating-face#1]
the event that captures the click and mouseover are getting an undefined, while looking for the value of the face in this line:

```
element.bind('click', function(e){
             try {
              ** var id = parseInt(e.srcElement.attributes.val.value);**
             } catch (e) {
               var id = 0;
             } finally {
               value_model.assign(scope, id);
               scope.$apply();
               scope.remove_class_face(id);
             }
           });

```

i change it to `var id = parseInt(e.originalEvent.srcElement.attributes.val.value);` and is working now.

Thanks.

**Comment by mapeveri** [comment]
@davidsa what browser do you use?. It works for me and I cannot reproduce the error.

**Comment by davidsa** [comment]
i think bower is downloading an older version of your code. 

and im using Chrome

**Comment by mapeveri** [comment]
No it is not, because it download the version 0.0.7. Newly run the command. It's very weird, The way that you tell me gives me error.

**Comment by mapeveri** [comment]
You can run example?. Does it work? This example: https://github.com/mapeveri/Angular-rating-face/tree/master/example
